server:
  port: 8000

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/ms?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: ms
    password: ms
  flyway:
    locations: classpath:/dbmigration
    baseline-on-migrate: true

logging:
  config : classpath:logback-boot.xml

