spring:
   flyway:
      baseline-on-migrate: true
      locations: classpath:/db/migration
   datasource:
      url: jdbc:mysql://127.0.0.1:3306/ms?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: ms
      password: ms
      driver-class-name: com.mysql.jdbc.Driver
   mvc:
      static-path-pattern: /static/**
logging:
  config: classpath:logback-boot.xml
  level:
    org:
      springframework:
        web: DEBUG
    root: INFO
server:
  port: 8000